language: java

os: linux
jdk: openjdk11
env:
  global:
    - PYTHON=3.6.0

before_install:
  - sudo apt-get install ruby
  - sudo gem install asciidoctor
  - pip install --user flake8==3.7.9
  - pip install --user python3-nose=1.3.7
  - pip install --user pygments
  - pip install --user six
  - pip install --user wheel
  - git clone https://github.com/machacekondra/pdoc.git pdoc
  - pip install --user ./pdoc -U

install:
  - mvn package -DskipTests

after_success:
  - sudo pip install ./sdk -U
  - travis_wait 20 pdoc --overwrite --html --html-dir=target/generated-html/ sdk/lib/ovirtsdk4/

deploy:
  - provider: script
    skip_cleanup: true
    script: automation/deploy-on-gh-pages.sh master
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: automation/deploy-on-gh-pages.sh tagged
    on:
      tags: true
