language: python

os: linux
python:
  - "3.6"


env:
  global:
    - PYCURL_CURL_CONFIG=/usr/local/opt/curl/bin/curl-config
    - LD_LIBRARY_PATH=/usr/local/opt/curl/lib:$LD_LIBRARY_PATH
    - PYCURL_SSL_LIBRARY=openssl

before_install:
  - sudo apt-get install ruby
  - sudo gem install asciidoctor
  - pip install flake8==3.7.9
  - pip install nose==1.3.7
  - pip install pygments
  - pip install six
  - pip install wheel
  - git clone https://github.com/machacekondra/pdoc.git pdoc
  - pip install ./pdoc -U

install:
  - mvn package -DskipTests

after_success:
  - sudo pip install ./sdk -U
  - travis_wait 20 pdoc --overwrite --html --html-dir=target/generated-html/ sdk/lib/ovirtsdk4/

deploy:
  - provider: script
    skip_cleanup: true
    script: automation/deploy-on-gh-pages.sh master
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
  - provider: script
    skip_cleanup: true
    script: automation/deploy-on-gh-pages.sh tagged
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
